---
title: 'Final Project: Project Plan Assignment'
author: "Yashar Mansouri, Joshua O'Steen, Christopher Hoffman"
date: "3/28/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Housing Market Analysis Group Project Plan

### App Title and Names of your group members

-   Housing Market Analysis of NYC Neighborhoods

-   Joshua O'Steen, Yashar Mansouri, Christopher Hoffmann

### Description of the problem to be analyzed in the Shiny App

-   The general purpose of the shiny app is to display the housing market trends (e.g., median house prices both listed and sold and median apartment rent) for NYC neighborhoods to the benefit of consumers and real estate investors.

### Proposed data sources

-   The data can be found on [StreetEasy Data](https://streeteasy.com/blog/data-dashboard/?agg=Total&metric=Inventory&type=Sales&bedrooms=Any%20Bedrooms&property=Any%20Property%20Type&minDate=2010-01-01&maxDate=2021-02-01&area=Flatiron,Brooklyn%20Heights#)
-   Other sources can include web scraping from rental sites such as zillow and trulia depending on available time and resources

## Concept for the Shiny App

### Overall Layout

-   Main user input side panel with choices such as neighborhood, budget, and other constraints for rentals.

-   Map visualization displaying data on NYC neighborhoods that highlights the selected boroughs or neighborhoods

-   Time series graphics for rent and sales price showing the trend over the recent years

## Data Analysis and Visualization with User Choices and Results

-   Line plot time series - AVG rent price - AVG home sales price per year

### Statistical Modeling with User Choices and Results (2)

-   Mean
-   Median
-   Linear regression to predict median price in the next 5 years

### Allocation of Responsibilities for the team

-   Yashar (Data Cleaning/Analysis/Statistical Modeling)

-   Joshua (Data Analysis/Cleaning/Shiny App Design)

-   Christopher (Data Analysis/Cleaning/Shiny App Design)

### Project Steps/Schedule

Note: weekly meeting on Sunday

March 28 -- Project plan created

April 4 -- Have all relevant data available, combined, and start the cleaning process.

April 11 -- Start creating the layout and basic elements of our app.

April 18 -- Continue creating shiny app with a focus on implementing the data. The data cleaning and process should be done at this point. All data should be usable.

April 25 -- Continue working on Shiny but be mostly finished. Begin stylization of shiny app and making it look "clean".

May 2 -- Clearing up anything that needs to be worked on. Quality check and ensure it is good to go.
